ALTER TABLE `nis_smtz` 
MODIFY COLUMN `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id' AFTER `YCBZ`,
ADD COLUMN `ZDYXH` int(0) NULL COMMENT '自定义序号(与自定义项目主键关联nis_zdytz主键)' AFTER `JGID`;

CREATE TABLE `nis_zdytz`  (
  `ZDYID` int(0) NOT NULL COMMENT '自定义id',
  `ZYH` int(0) NULL COMMENT '住院号',
  `ZDYMC` varchar(50) NULL COMMENT '自定义名称',
  `DQZS` int(0) NULL COMMENT '当前周数',
  `JGID` int(0) NULL COMMENT '机构id',
  `PYDM` varchar(50) NULL COMMENT '拼音代码',
  PRIMARY KEY (`ZDYID`)
) COMMENT = '体温单自定义表';

ALTER TABLE `nis_smtz` 
MODIFY COLUMN `BRCH` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '病人床号' AFTER `BRBQ`;

CREATE TABLE `nis_gdhtwxysb`  (
  `JLXH` int(0) NOT NULL COMMENT '主键',
  `ZYH` int(0) NULL DEFAULT NULL COMMENT '住院号',
  `MBLX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板类型',
  `GWFXGD` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '高危风险管道',
  `ZWFXGD` varchar(255) NULL DEFAULT NULL COMMENT '中危风险管道',
  `DWFXGD` varchar(255) NULL DEFAULT NULL COMMENT '低危风险管道',
  `QT` varchar(255) NULL DEFAULT NULL COMMENT '其他',
  `HLCS` varchar(255) NULL COMMENT '护理措施',
  `HSQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护士签名',
  `RQ` datetime(0) NULL DEFAULT NULL COMMENT '日期',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  `ZF` int(0) NULL DEFAULT NULL COMMENT '总分',
  PRIMARY KEY (`JLXH`)
) COMMENT = '住院患者管道滑脱危险因素评估表';


CREATE TABLE `nis_cghljld`  (
  `JLXH` int(0) NOT NULL COMMENT '主键',
  `ZYH` int(0) NULL DEFAULT NULL COMMENT '住院号',
  `MBLX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板类型',
  `TW` decimal(10, 2) NULL DEFAULT NULL COMMENT '体温',
  `MB` int(0) NULL DEFAULT NULL COMMENT '脉搏',
  `HX` int(0) NULL DEFAULT NULL COMMENT '呼吸',
  `BP` decimal(10, 2) NULL DEFAULT NULL COMMENT 'BP',
  `TTPF` int(0) NULL DEFAULT NULL COMMENT '疼痛评分',
  `ZLNLPF` int(0) NULL DEFAULT NULL COMMENT '自理能力评分',
  `DGPF` int(0) NULL DEFAULT NULL COMMENT '导管评分',
  `YLXSS` int(0) NULL DEFAULT NULL COMMENT '压力性损伤',
  `DDZCPF` int(0) NULL DEFAULT NULL COMMENT '跌倒坠床评分',
  `JCHL` varchar(255) NULL COMMENT '基础护理',
  `HLXJ` varchar(255) NULL COMMENT '护理宣教',
  `YY` varchar(50) NULL COMMENT '营养',
  `JSXL` varchar(50) NULL COMMENT '精神心理',
  `ZDYLONE` int(0) NULL COMMENT '自定义列1',
  `ZDYLTWO` int(0) NULL COMMENT '自定义列2',
  `ZDYLTHREE` int(0) NULL COMMENT '自定义列3',
  `ZDYLFOUR` int(0) NULL COMMENT '自定义列4',
  `ZDYLFIVE` int(0) NULL COMMENT '自定义列5',
  `ZDYLSIX` int(0) NULL COMMENT '自定义列6',
  `HLJL` varchar(255) NULL COMMENT '护理记录',
  `HSQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护士签名',
  `RQ` datetime(0) NULL DEFAULT NULL COMMENT '日期',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  `SMTZID` int(0) NULL COMMENT '生命体征关联id',
  `ZLNLID` int(0) NULL COMMENT '自理能力关联id',
  `DGID` int(0) NULL COMMENT '导管关联id',
  `YLXSSID` int(0) NULL COMMENT '压力性损伤关联id',
  `DDZCID` int(0) NULL COMMENT '跌倒坠床关联id',
  PRIMARY KEY (`JLXH`)
) COMMENT = '常规护理记录单';

CREATE TABLE `nis_ddzcpgb`  (
  `JLXH` int(0) NOT NULL COMMENT '主键',
  `ZYH` int(0) NULL DEFAULT NULL COMMENT '住院号',
  `MBLX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板类型',
  `DDS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '跌倒病史',
  `NL` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '年龄',
  `ZD` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '诊断',
  `XZFZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '行走辅助',
  `ZGZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '照顾者',
  `BT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '步态',
  `JSZT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '精神状态',
  `SYJMYW` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '使用药物',
  `XW` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '行为',
  `TSJ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '听/视觉',
  `GTNL` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '沟通能力',
  `XY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '眩晕',
  `PX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '排泄',
  `DXGW` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '单项高危',
  `HSQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护士签名',
  `HLCS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护理措施',
  `ZF` int(0) NULL DEFAULT NULL COMMENT '总分',
  `RQ` datetime(0) NULL DEFAULT NULL COMMENT '日期',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构',
  PRIMARY KEY (`JLXH`)
) COMMENT = '住院患者跌倒、坠床危险因素评估表';


ALTER TABLE `cis_hzyz` 
ADD COLUMN `TZZT` int(0) NULL COMMENT '通知状态(1:已通知,0:未通知)' AFTER `KJYWSP`,
ADD COLUMN `TZTIME` datetime(0) NULL COMMENT '通知时间' AFTER `TZZT`,
ADD COLUMN `TZGH` int(0) NULL COMMENT '通知工号' AFTER `TZTIME`;

ALTER TABLE `cis_hzyz_zt` 
ADD COLUMN `TZZT` int(0) NULL DEFAULT NULL COMMENT '通知状态(1:已通知,0:未通知)' AFTER `YZLX`,
ADD COLUMN `TZTIME` datetime(0) NULL DEFAULT NULL COMMENT '通知时间' AFTER `TZZT`,
ADD COLUMN `TZGH` int(0) ZEROFILL NULL DEFAULT NULL COMMENT '通知工号' AFTER `TZTIME`;

ALTER TABLE `im_hzry` 
ADD COLUMN `TZZT` int(0) NULL DEFAULT NULL COMMENT '通知状态(1:出院通知,2:待出院通知,3:入院通知,4:待入院通知,0:未通知)' AFTER `jzdyh`,
ADD COLUMN `TZTIME` datetime(0) NULL DEFAULT NULL COMMENT '通知时间' AFTER `TZZT`,
ADD COLUMN `TZGH` int(0) ZEROFILL NULL DEFAULT NULL COMMENT '通知工号' AFTER `TZTIME`;

CREATE TABLE `nis_zdytzxm`  (
  `XMDM` int(0) NULL COMMENT '项目代码(主键)',
  `ZDYMC` varchar(50) NULL COMMENT '自定义名称',
  `ZFPB` int(0) NOT NULL COMMENT '作废判别',
  `PYDM` varchar(50) NOT NULL COMMENT '拼音代码',
  `JGID` int(0) NULL COMMENT '机构id',
  PRIMARY KEY (`ZFPB`)
) COMMENT = '自定义体征项目';

ALTER TABLE `nis_zdytz` 
ADD COLUMN `XMDM` int(0) NULL COMMENT '项目代码' AFTER `PYDM`;

ALTER TABLE `nis_smtz` 
ADD COLUMN `SJD` int(0) NULL COMMENT '时间段' AFTER `ZDYXH`;

CREATE TABLE `nis_smtz_batch`  (
  `CJH` int(0) NOT NULL COMMENT '采集号',
  `CJZH` int(0) NOT NULL COMMENT '采集组号（仅为方便程序处理）',
  `XMH` int(0) NULL DEFAULT NULL COMMENT '项目号（体征项目）',
  `JHBZ` int(0) NOT NULL COMMENT '计划标志（0：临时；1：计划）',
  `CJSJ` datetime(0) NOT NULL COMMENT '采集时间（测量时间）',
  `ZYH` int(0) NOT NULL COMMENT '住院号',
  `BRKS` int(0) NULL DEFAULT NULL COMMENT '病人科室',
  `BRBQ` int(0) NULL DEFAULT NULL COMMENT '病人病区',
  `BRCH` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '病人床号',
  `TZNR` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '体征内容',
  `XMXB` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '项目下标（体温类型等）',
  `FCBZ` int(0) NOT NULL COMMENT '复测标志（0：首测  1：复测）',
  `FCGL` int(0) NULL DEFAULT NULL COMMENT '复测关联（FCBZ=1，记录需要复测记录的采集号）',
  `TWDXS` int(0) NULL DEFAULT NULL COMMENT '体温单显示（0：不显示 1：显示，显示在体温单的‘空白栏’或‘其他’栏内）',
  `JLSJ` datetime(0) NOT NULL COMMENT '记录时间（实际录入系统的时间）',
  `JLGH` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '记录人员',
  `ZFBZ` int(0) NOT NULL COMMENT '作废标志（0：有效 1：已作废）',
  `BZXX` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注信息（复测方法、辅助呼吸等）',
  `YCBZ` int(0) NOT NULL COMMENT '异常标志（-2：低  -1：偏低  0：正常  1：偏高  2：高）',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  `ZDYXH` int(0) NULL DEFAULT NULL COMMENT '自定义序号(与自定义项目主键关联nis_zdytz主键)',
  `SJD` int(0) NULL DEFAULT NULL COMMENT '时间段(2,6,10,14,18,22)',
  PRIMARY KEY (`CJH`) USING BTREE,
  INDEX `IDX_BQ_SMTZ_BRBQ`(`BRBQ`) USING BTREE,
  INDEX `IDX_BQ_SMTZ_CJSJ`(`CJSJ`) USING BTREE,
  INDEX `IDX_BQ_SMTZ_CJZH`(`CJZH`) USING BTREE,
  INDEX `IDX_BQ_SMTZ_XMH`(`XMH`) USING BTREE,
  INDEX `IDX_BQ_SMTZ_ZYH`(`ZYH`) USING BTREE
) COMMENT = '生命体征批量保存表';

ALTER TABLE `im_zkjl` 
ADD COLUMN `TZZT` int(0) NULL DEFAULT NULL COMMENT '通知状态(1:转出通知,2:转入通知,0:未通知)' AFTER `JGID`,
ADD COLUMN `TZTIME` datetime(0) NULL DEFAULT NULL COMMENT '通知时间' AFTER `TZZT`,
ADD COLUMN `TZGH` int(10) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT '通知工号' AFTER `TZTIME`;

CREATE TABLE `nis_lzdngpgb`  (
  `JLXH` int(0) NOT NULL COMMENT '主键',
  `ZYH` int(0) NULL DEFAULT NULL COMMENT '住院号',
  `MBLX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板类型',
  `YBQK` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '一般情况',
  `DNGLX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '导尿管类型',
  `LZSJ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '留置时间',
  `NYXZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '尿液性状',
  `PGCX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '膀胱冲洗',
  `HLCS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护理措施',
  `HSQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护士签名',
  `RQ` datetime(0) NULL DEFAULT NULL COMMENT '日期',
  `ZF` int(0) NULL DEFAULT NULL COMMENT '总分',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  PRIMARY KEY (`JLXH`)
) COMMENT = '留置导尿管感染风险因素评估表';

CREATE TABLE `nis_zxjmpgb`  (
  `JLXH` int(0) NOT NULL COMMENT '主键',
  `ZYH` int(0) NULL DEFAULT NULL COMMENT '住院号',
  `MBLX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板类型',
  `NL` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '年龄',
  `JCJB` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '基础疾病',
  `ZGBW` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '置管部位',
  `ZGZT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '置管状态',
  `LZSJ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '留置时间',
  `DGCZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '导管材质',
  `DGQS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '导管腔数',
  `SYJK` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '输液接口',
  `SZYT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '输注液体',
  `HLCS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护理措施',
  `HSQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护士签名',
  `RQ` datetime(0) NULL DEFAULT NULL COMMENT '日期',
  `ZF` int(0) NULL DEFAULT NULL COMMENT '总分',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  PRIMARY KEY (`JLXH`)
) COMMENT = '中心静脉导管相关性感染风险因素评估表';


CREATE TABLE `nis_fsspgb`  (
  `JLXH` int(0) NOT NULL COMMENT '主键',
  `ZYH` int(0) NULL DEFAULT NULL COMMENT '住院号',
  `MBLX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板类型',
  `YBQK` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '一般情况',
  `TSJB` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '导尿管类型',
  `SSHZL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '尿液性状',
  `HLCS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护理措施',
  `HSQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护士签名',
  `RQ` datetime(0) NULL DEFAULT NULL COMMENT '日期',
  `ZF` int(0) NULL DEFAULT NULL COMMENT '总分',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  PRIMARY KEY (`JLXH`)
) COMMENT = '深静脉血栓风险评估表';

CREATE TABLE `nis_sjkjld`  (
  `JLXH` int(0) NOT NULL COMMENT '主键',
  `ZYH` int(0) NULL DEFAULT NULL COMMENT '住院号',
  `MBLX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板类型',
  `SZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '神志',
  `GSLPF` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '格拉斯评分',
  `TKZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '瞳孔左',
  `TKY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '瞳孔右',
  `TKZDGFS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '瞳孔左对光放射',
  `TKYDGFS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '瞳孔右对光放射',
  `ZKHLONE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '自定义转科护理1',
  `ZKHLTWO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '自定义转科护理2',
  `TW` decimal(10, 2) NULL DEFAULT NULL COMMENT '体温',
  `MB` int(0) NULL DEFAULT NULL COMMENT '脉搏',
  `HX` int(0) NULL DEFAULT NULL COMMENT '呼吸',
  `BP` decimal(10, 2) NULL DEFAULT NULL COMMENT 'BP',
  `TTPF` int(0) NULL DEFAULT NULL COMMENT '疼痛评分',
  `ZLNLPF` int(0) NULL DEFAULT NULL COMMENT '自理能力评分',
  `DGPF` int(0) NULL DEFAULT NULL COMMENT '导管评分',
  `YLXSS` int(0) NULL DEFAULT NULL COMMENT '压力性损伤',
  `DDZCPF` int(0) NULL DEFAULT NULL COMMENT '跌倒坠床评分',
  `JCHL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '基础护理',
  `HLXJ` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护理宣教',
  `YY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '营养',
  `JSXL` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '精神心理',
  `HLJL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护理记录',
  `HSQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护士签名',
  `RQ` datetime(0) NULL DEFAULT NULL COMMENT '日期',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  `SMTZID` int(0) NULL DEFAULT NULL COMMENT '生命体征关联id',
  `ZLNLID` int(0) NULL DEFAULT NULL COMMENT '自理能力关联id',
  `DGID` int(0) NULL DEFAULT NULL COMMENT '导管关联id',
  `YLXSSID` int(0) NULL DEFAULT NULL COMMENT '压力性损伤关联id',
  `DDZCID` int(0) NULL DEFAULT NULL COMMENT '跌倒坠床关联id',
  PRIMARY KEY (`JLXH`)
) COMMENT = '神经科记录单';


CREATE TABLE `nis_allzxd`  (
  `JLXH` int(0) NOT NULL COMMENT '主键',
  `ZYH` int(0) NULL DEFAULT NULL COMMENT '住院号',
  `MBLX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板类型',
  `ZH` int(0) NULL DEFAULT NULL COMMENT '组号',
  `HLZD` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护理诊断',
  `QT` varchar(255) NULL COMMENT '护理诊断其他',
  `HLMB` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护理目标',
  `HLCS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护理措施',
  `HLSJ` datetime(0) NULL DEFAULT NULL COMMENT '护理时间',
  `XGPJSJ` datetime(0) NULL DEFAULT NULL COMMENT '效果评价时间',
  `XGPJ` varchar(255) NULL COMMENT '效果评价',
  `HSQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护士签名',
  `YSQM` varchar(50) NULL COMMENT '医生签名',
  `RQ` datetime(0) NULL DEFAULT NULL COMMENT '日期',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  PRIMARY KEY (`JLXH`)
) COMMENT = '所有护理执行单';


CREATE TABLE `nis_ylxsscbd`  (
  `JLXH` int(0) NOT NULL COMMENT '主键',
  `ZYH` int(0) NULL DEFAULT NULL COMMENT '住院号',
  `MBLX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板类型',
  `FSQK` varchar(50) NULL DEFAULT NULL COMMENT '翻身情况',
  `BMI` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'BMI',
  `DDBXZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '低蛋白血症',
  `JS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '进食',
  `TLB` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '糖尿病',
  `PGZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '评估者',
  `RQ` datetime(0) NULL DEFAULT NULL COMMENT '日期',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  `BGSJ` datetime(0) NULL DEFAULT NULL COMMENT '报告日期',
  `SSSJ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '手术时间',
  `SSSZY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '手术中舒张压',
  PRIMARY KEY (`JLXH`)
)COMMENT = '压力性损伤预报、传报单';

CREATE TABLE `nis_ylxssjksf`  (
  `JLXH` int(0) NOT NULL COMMENT '主键',
  `CBDJLXH` int(0) NULL DEFAULT NULL COMMENT '主表记录序号',
  `PF` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'Braden评分',
  `YB` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '预报≤12分',
  `YNFS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '院内发生',
  `YWDR` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '院外带入',
  `BW` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '部位',
  `DX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '大小',
  `SKFQ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '伤口分期',
  `JBYS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '基部颜色',
  `SC` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '渗出',
  `CMCL` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '疮面处理',
  `HLCS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护理措施',
  `HSZQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护士长签名',
  `HLBDD` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护理部督导',
  `RQ` datetime(0) NULL DEFAULT NULL COMMENT '日期',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  PRIMARY KEY (`JLXH`)
) COMMENT = '压力性损伤预报、传报单(监控随访)';

CREATE TABLE `nis_ylxsszg`  (
  `JLXH` int(0) NOT NULL COMMENT '主键',
  `CBDJLXH` int(0) NULL DEFAULT NULL COMMENT '主表记录序号',
  `WFS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '未发生',
  `FS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '发生',
  `JBZG` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '疾病转归',
  `YLXSSZG` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '压力性损伤转归',
  `QM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '签名',
  `RQ` datetime(0) NULL DEFAULT NULL COMMENT '日期',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  PRIMARY KEY (`JLXH`)
) COMMENT = '压力性损伤预报、传报单(转归情况)';


CREATE TABLE `nis_ryhld`  (
  `JLXH` int(0) NOT NULL COMMENT '主键',
  `ZYH` int(0) NULL DEFAULT NULL COMMENT '住院号',
  `MBLX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板类型',
  `JZFS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '就诊方式',
  `RYFS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '入院方式',
  `ZLLY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '资料来源',
  `GMS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '过敏史',
  `GMYW` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '过敏史药物',
  `WHCD` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '文化程度',
  `MZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '民族',
  `FYZF` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '费用支出',
  `ZY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '职业',
  `JZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '居住',
  `ZJXY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '宗教信仰',
  `SMTZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '生命体征',
  `XL` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '心率',
  `HX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '呼吸',
  `XY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '血压',
  `TTPF` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '疼痛评分',
  `PGGJ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '评估工具',
  `SL` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '视力',
  `SLQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '视力其他',
  `TL` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '听力',
  `TLQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '听力其他',
  `KQQK` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '口腔情况',
  `KQQKQT` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '口腔情况其他',
  `YY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '语言',
  `YYQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '语言其他',
  `PF` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '皮肤',
  `PFQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '皮肤其他',
  `DG` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '导管',
  `DGQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '导管其他',
  `JBSS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '基本膳食',
  `JJ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '禁忌',
  `PH` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '偏好',
  `ZLYS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '治疗饮食',
  `SY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '食欲',
  `SYQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '食欲其他',
  `SM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '睡眠',
  `SMQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '睡眠其他',
  `PB` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '排便',
  `PBQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '排便其他',
  `PN` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '排尿',
  `PNQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '排尿其他',
  `SH` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '嗜好',
  `SHY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '嗜好烟',
  `SHJ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '嗜好酒',
  `QXZT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '情绪状态',
  `QXZTQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '情绪状态其他',
  `JBRZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '疾病认知',
  `ZYGL` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '住院顾虑',
  `ZYGLQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '住院顾虑其他',
  `HYZT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '婚姻状态',
  `SG` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '身高',
  `TZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '体重',
  `TZZS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '体重指数',
  `BMI` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'BMI',
  `TZDS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '体重丢失',
  `SSSR` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '膳食摄入',
  `JYDX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '教育对象',
  `XXYY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '学习意愿',
  `HZYZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '患者语种',
  `FY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '方言',
  `WY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '外语',
  `XXNL` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '学习能力',
  `XXFS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '学习方式',
  `XXFSQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '学习方式其他',
  `TSXQ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '特殊需求',
  `TSRQ` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '特殊人群',
  `CYQX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '出院去向',
  `CYQXQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '出院去向其他',
  `CYHZGZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '出院后照顾者',
  `JTGJXQ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '交通工具需求',
  `JTGJXQQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '交通工具需求其他',
  `HSQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护士签名',
  `HSQMRQ` datetime(0) NULL DEFAULT NULL COMMENT '护士签名日期',
  `HSZQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护士长签名',
  `HSZQMRQ` datetime(0) NULL DEFAULT NULL COMMENT '护士长签名日期',
  `YSQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '医师签名',
  `YSQMRQ` datetime(0) NULL DEFAULT NULL COMMENT '医师签名日期',
  `RQ` datetime(0) NULL DEFAULT NULL COMMENT '日期',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  PRIMARY KEY (`JLXH`)
) COMMENT = '入院护理评估单';


CREATE TABLE `nis_zdyxm`  (
  `XMDM` int(0) NOT NULL COMMENT '项目代码(主键)',
  `XMMC` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '项目名称',
  `ZFPB` int(0) NULL DEFAULT NULL COMMENT '作废判别',
  `PYDM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '拼音代码',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  PRIMARY KEY (`XMDM`)
) COMMENT = '护理记录单自定义项目';


CREATE TABLE `nis_hljldzdy`  (
  `ZDYID` int(0) NOT NULL COMMENT '自定义id',
  `ZYH` int(0) NULL COMMENT '住院号',
  `MBLX` varchar(50) NULL COMMENT '模板类型',
  `XMDM` int(0) NULL COMMENT '自定义项目代码',
  `ZDYMC` varchar(50) NULL COMMENT '自定义名称',
  `ZDYNR` varchar(255) NULL COMMENT '自定义内容',
  `JLXH` int(0) NULL COMMENT '护理记录单JLXH',
  `JGID` int(0) NULL COMMENT '机构id',
  PRIMARY KEY (`ZDYID`)
) COMMENT = '护理记录单自定义内容';


/*新增留观病区 留观科室字典*/
ALTER TABLE `dic_kszd`
ADD COLUMN `LGBQ` varchar(1) NULL DEFAULT 0 COMMENT '是否是留观病区 1：是 0 :否' AFTER `BBGB`,
ADD COLUMN `LGKS` varchar(1) NULL DEFAULT 0 COMMENT '是否是留观科室 1：是 0 :否' AFTER `LGBQ`;

/*新增住院业务类型*/
ALTER TABLE `im_hzry`
ADD COLUMN `ywlx` varchar(1) NULL COMMENT '1:住院 2：留观' AFTER `TZGH`;

CREATE TABLE `nis_fssrisk`  (
  `JLXH` int(0) NOT NULL COMMENT '主键',
  `ZYH` int(0) NULL DEFAULT NULL COMMENT '住院号',
  `MBLX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板类型',
  `BS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'PTE或DVT病史',
  `SSGZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '1月内手术或骨折',
  `HDXZL` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '活动性肿瘤',
  `XL` varchar(50) NULL COMMENT '心率（次/min）',
  `KX` varchar(50) NULL COMMENT '咯血',
  `XZTT` varchar(50) NULL COMMENT '单侧下肢疼痛',
  `XZSZ` varchar(50) NULL COMMENT '下肢深静脉触痛及单侧下肢水肿',
  `NLDY` varchar(50) NULL COMMENT '年龄＞65岁',
  `XYGN` varchar(50) NULL COMMENT '血液高凝',
  `XZB` varchar(50) NULL COMMENT '心脏病',
  `HLCS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护理措施',
  `HSQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护士签名',
  `RQ` datetime(0) NULL DEFAULT NULL COMMENT '日期',
  `ZF` int(0) NULL DEFAULT NULL COMMENT '总分',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  PRIMARY KEY (`JLXH`)
) COMMENT = '肺栓塞风险因素评估表';

ALTER TABLE `cis_hzyz` 
MODIFY COLUMN `SCBZ` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '上传标志' AFTER `ZFYP`;

ALTER TABLE `cis_hzyz_zt` 
MODIFY COLUMN `SCBZ` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '上传标志' AFTER `ZFYP`;

ALTER TABLE `cis_sxyy` COMMENT = '备血申请单输血原因';
ALTER TABLE `cis_zy_hzsq` COMMENT = '住院会诊申请单主表';
ALTER TABLE `cis_zy_hzyj` 
MODIFY COLUMN `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id' AFTER `QMSJ`,
COMMENT = '住院会诊申请意见';
ALTER TABLE `cis_zy_hzyqdx` 
MODIFY COLUMN `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id' AFTER `YQYS`,
COMMENT = '住院会诊申请邀请对象';

ALTER TABLE `nis_qtyz` 
MODIFY COLUMN `YZXH` int(0) NOT NULL COMMENT '医嘱序号(主键)' FIRST,
MODIFY COLUMN `YZMC` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '医嘱名称' AFTER `YZXH`,
MODIFY COLUMN `SRDM` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '输入代码' AFTER `YZMC`,
MODIFY COLUMN `YZLB` int(0) NULL DEFAULT NULL COMMENT '医嘱类别' AFTER `SRDM`,
MODIFY COLUMN `TSBZ` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '特殊标志' AFTER `YZLB`,
MODIFY COLUMN `ZFBZ` int(0) NULL DEFAULT NULL COMMENT '作废标志' AFTER `TSBZ`,
MODIFY COLUMN `YZPX` int(0) NULL DEFAULT NULL COMMENT '医嘱排序' AFTER `ZFBZ`,
MODIFY COLUMN `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id' AFTER `YZPX`,
COMMENT = '病区其他医嘱';

ALTER TABLE `nis_tfmx` COMMENT = '退费明细 ';
ALTER TABLE `nis_tzxm` 
MODIFY COLUMN `XMDW` int(0) NULL DEFAULT NULL COMMENT '自定义项目代码' AFTER `TZLX`,
COMMENT = '病区_体征项目';
ALTER TABLE `nis_yzdy` COMMENT = '医嘱本打印';
ALTER TABLE `im_bedresev` COMMENT = '床位预约表';

ALTER TABLE `im_cwsz` 
MODIFY COLUMN `JCRQ` datetime(0) NULL DEFAULT NULL COMMENT '未知' AFTER `ZDYCW`,
MODIFY COLUMN `SCBZ` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '上传标志' AFTER `JCRQ`;

ALTER TABLE `im_hcmx` 
MODIFY COLUMN `SCBZ` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '上传标志' AFTER `CZGH`;

ALTER TABLE `im_fee_fymx` 
MODIFY COLUMN `SCBZ` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '上传标志' AFTER `DZBL`,
MODIFY COLUMN `mxscbz` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '明细上传标志' AFTER `CLDYM`,
MODIFY COLUMN `mxzdh` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '明细账单号' AFTER `mxscbz`,
MODIFY COLUMN `MXJSBZ` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '明细结算标志' AFTER `mxzdh`,
MODIFY COLUMN `JZDYH` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '就诊单元号' AFTER `MXJSBZ`;

ALTER TABLE `im_fee_fymx_yj` 
MODIFY COLUMN `XFLSH` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '细分流水号' AFTER `SCBZ`;

ALTER TABLE `im_hzry` 
MODIFY COLUMN `ZHBZ` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '账户标志' AFTER `MZZD`,
MODIFY COLUMN `SCBZ` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '上传标志' AFTER `ZHBZ`,
MODIFY COLUMN `XZQHDM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '行政区划代码' AFTER `MZLB`,
MODIFY COLUMN `jzdyh` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '就诊单元号' AFTER `ICD10BM`;

ALTER TABLE ``im_fee_fymx_js` 
MODIFY COLUMN `XFLSH` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '细分流水号' AFTER `SCBZ`,
MODIFY COLUMN `mxscbz` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '明细上传标志' AFTER `CLDYM`,
MODIFY COLUMN `mxzdh` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '明细账单号' AFTER `mxscbz`,
MODIFY COLUMN `MXJSBZ` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '明细结算标志' AFTER `mxzdh`,
MODIFY COLUMN `JZDYH` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '就诊单元号' AFTER `MXJSBZ`;

ALTER TABLE `im_jsmx` 
MODIFY COLUMN `SCBZ` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '上传标志' AFTER `ZLJE`;

ALTER TABLE `im_jszf` 
MODIFY COLUMN `MZLB` int(0) NULL DEFAULT NULL COMMENT '门诊类别' AFTER `HZRQ`;

ALTER TABLE `im_rcjl` 
MODIFY COLUMN `SCBZ` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '上传标志' AFTER `BZXX`;

ALTER TABLE `im_ryzd` 
MODIFY COLUMN `SCBZ` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '上传标志' AFTER `TXBZ`,
MODIFY COLUMN `ZDRQ` datetime(0) NULL DEFAULT NULL COMMENT '诊断日期' AFTER `SCBZ`;

ALTER TABLE `im_tbkk` 
MODIFY COLUMN `SCBZ` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '上传标志' AFTER `ZCPB`;

ALTER TABLE `im_twdnr` 
MODIFY COLUMN `ZYH` int(0) NULL DEFAULT NULL COMMENT '住院号' FIRST,
MODIFY COLUMN `ZYHM` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '住院号码' AFTER `ZYH`,
MODIFY COLUMN `CZNR` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '操作内容' AFTER `ZYHM`,
MODIFY COLUMN `CZSJ` datetime(0) NULL DEFAULT NULL COMMENT '操作时间' AFTER `CZNR`,
MODIFY COLUMN `ID` int(0) NOT NULL COMMENT '主键id' AFTER `CZSJ`,
MODIFY COLUMN `BRCH` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '病人床号' AFTER `ID`,
MODIFY COLUMN `BRXM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '病人姓名' AFTER `BRCH`,
COMMENT = '住院体温单内容';


ALTER TABLE `im_jzxx` 
MODIFY COLUMN `ZXJZFY` int(0) NULL DEFAULT NULL COMMENT '中心就诊费用' AFTER `QZSJ`,
MODIFY COLUMN `GRXJZF` int(0) NULL DEFAULT NULL COMMENT '个人现金支付' AFTER `ZXJZFY`,
MODIFY COLUMN `BCZHZF` int(0) NULL DEFAULT NULL COMMENT '本次账户支付' AFTER `GRXJZF`,
MODIFY COLUMN `TCZC` int(0) NULL DEFAULT NULL COMMENT '统筹支出' AFTER `BCZHZF`,
MODIFY COLUMN `DBZC` int(0) NULL DEFAULT NULL COMMENT '大病支出' AFTER `TCZC`,
MODIFY COLUMN `AZQGFY` int(0) NULL DEFAULT NULL COMMENT '按照全国费用' AFTER `DBZC`;

ALTER TABLE `im_zyjs` 
MODIFY COLUMN `SCBZ` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '上传标志' AFTER `BRXZ`;

ALTER TABLE `cis_hzyz` 
ADD COLUMN `ZFSJ` datetime(0) NULL COMMENT '医嘱作废时间' AFTER `TZGH`;

ALTER TABLE `cis_hzyz_zt` 
ADD COLUMN `ZFSJ` datetime(0) NULL COMMENT '医嘱作废时间' AFTER `TZGH`;


ALTER TABLE `mess_cljl` 
ADD COLUMN `yw_type` int(0) NULL COMMENT '业务类型(1:住院护士站,2:住院医生站)' AFTER `c_time`;

CREATE TABLE `mess_jsjl`  (
  `mess_jsjl_id` int(0) NOT NULL COMMENT '消息接收记录主键',
  `mess_id` int(0) NOT NULL COMMENT '消息主键',
  `ks_id` int(0) NULL DEFAULT NULL COMMENT '科室ID',
  `user_id` int(0) NULL DEFAULT NULL COMMENT '用户ID',
  `js_time` datetime(0) NULL DEFAULT NULL COMMENT '消息接收时间',
  `yw_type` int(0) NULL DEFAULT NULL COMMENT '业务类型(1:住院护士站,2:住院医生站)',
  PRIMARY KEY (`mess_jsjl_id`)
) COMMENT = '消息危急值接收记录';

ALTER TABLE `cis_bxsqd` 
MODIFY COLUMN `SXYY` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '输血目的' AFTER `LCXX`,
ADD COLUMN `YDSXZL` decimal(10, 4) NULL COMMENT '预定输血总量' AFTER `SQRHXX`,
ADD COLUMN `SXQJC` varchar(1) NULL COMMENT '受血者输血前检查(1:是,0:否)' AFTER `YDSXZL`,
ADD COLUMN `SXZSD` varchar(1) NULL COMMENT '受血者属地(1:本市,2:外埠)' AFTER `SXQJC`,
MODIFY COLUMN `SXSBS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '继往输血史(无/有/未说明)' AFTER `SQRHXX`,
ADD COLUMN `YCS` varchar(50) NULL COMMENT '孕产史' AFTER `SXSBS`,
ADD COLUMN `YZS` varchar(50) NULL COMMENT '移植史' AFTER `YCS`,
ADD COLUMN `QT` varchar(50) NULL COMMENT '其他' AFTER `YZS`,
ADD COLUMN `YDSXRQ` datetime(0) NULL COMMENT '预定输血日期' AFTER `BXB`,
ADD COLUMN `SXTYS` varchar(255) NULL COMMENT '输血同意书' AFTER `YDSXRQ`,
ADD COLUMN `YXZ` varchar(50) NULL COMMENT '用血证' AFTER `SXTYS`,
ADD COLUMN `ZZYS` varchar(50) NULL COMMENT '主治医师' AFTER `YXZ`,
ADD COLUMN `SJYS` varchar(50) NULL COMMENT '上级医师' AFTER `ZZYS`,
ADD COLUMN `KZR` varchar(50) NULL COMMENT '科主任' AFTER `SJYS`,
ADD COLUMN `YYWK` varchar(50) NULL COMMENT '院医务科' AFTER `KZR`;


ALTER TABLE `im_rcjl` 
MODIFY COLUMN `BZXX` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '问题医嘱' AFTER `CYFS`,
ADD COLUMN `SF` varchar(255) NULL COMMENT '随访信息' AFTER `SCBZ`;

ALTER TABLE `nis_sjkjld` 
CHANGE COLUMN `GSLPF` `GLSPF` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '格拉斯评分' AFTER `SZ`;
