ALTER TABLE `im_hzry` 
ADD COLUMN `FZRYS` varchar(10) NULL COMMENT '副主任医师' AFTER `RYTJ`,
ADD COLUMN `ZRHS` varchar(10) NULL COMMENT '责任护士' AFTER `FZRYS`,
ADD COLUMN `ZGHS` varchar(10) NULL COMMENT '主管护士' AFTER `ZRHS`;