ALTER TABLE `nis_rjbfhld` 
ADD COLUMN `MZQT` varchar(50) NULL COMMENT '民族其他' AFTER `MZ`,
ADD COLUMN `FYZFQT` varchar(50) NULL COMMENT '费用支付其他' AFTER `FYZF`,
ADD COLUMN `ZYQT` varchar(50) NULL COMMENT '职业其他' AFTER `ZY`,
ADD COLUMN `ZJXYQT` varchar(50) NULL COMMENT '宗教信仰其他' AFTER `ZJXY`,
ADD COLUMN `SKQKWG` varchar(50) NULL COMMENT '伤口情况外观' AFTER `SKQK`,
MODIFY COLUMN `HZZG` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '患者转归出院' AFTER `ZGQK`,
ADD COLUMN `HZZGZK` varchar(50) NULL COMMENT '患者转归转科' AFTER `HZZG`;