CREATE TABLE `nis_rjbfhld`  (
  `JLXH` int(0) NOT NULL COMMENT '主键',
  `ZYH` int(0) NULL DEFAULT NULL COMMENT '住院号',
  `MBLX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板类型',
  `RYFS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '入院方式',
  `RYFSQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '入院方式其他',
  `YS` varchar(50) NULL COMMENT '意识',
  `PFQK` varchar(50) NULL COMMENT '皮肤情况',
  `PFQKQT` varchar(50) NULL COMMENT '皮肤情况其他',
  `ZLLY` varchar(50) NULL COMMENT '资料来源',
  `ZLLYQT` varchar(50) NULL COMMENT '资料来源其他',
  `GMS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '过敏史',
  `GMSQT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '过敏史其他',
  `WHCD` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '文化程度',
  `MZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '民族',
  `FYZF` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '费用支出',
  `ZY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '职业',
  `ZJXY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '宗教信仰',
  `SMTZ` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '生命体征',
  `XL` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '心率',
  `HX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '呼吸',
  `SSY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '收缩压',
  `SZY` varchar(50) NULL COMMENT '舒张压',
  `SG` varchar(50) NULL COMMENT '身高',
  `TZ` varchar(50) NULL COMMENT '体重',
  `BMI` varchar(50) NULL COMMENT '体重指数BMI',
  `TTPF` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '疼痛评分',
  `QTZKPF` varchar(50) NULL COMMENT '其他专科评估',
  `RYXJ` varchar(50) NULL COMMENT '入院宣教',
  `SQZD` varchar(50) NULL COMMENT '术前指导',
  `HZJR` varchar(50) NULL COMMENT '患者今日',
  `FHBF` varchar(50) NULL COMMENT '返回病房',
  `SZ` varchar(50) NULL COMMENT '神志',
  `HLTW` varchar(50) NULL COMMENT '护理体温',
  `HLXL` varchar(50) NULL COMMENT '护理心率',
  `HLHX` varchar(50) NULL COMMENT '护理呼吸',
  `HLSSY` varchar(50) NULL COMMENT '护理收缩压',
  `HLSZY` varchar(50) NULL COMMENT '护理舒张压',
  `HLTTPF` varchar(50) NULL COMMENT '护理疼痛评分',
  `YSQK` varchar(50) NULL COMMENT '饮食',
  `TW` varchar(50) NULL COMMENT '体位',
  `HLYS` varchar(50) NULL COMMENT '护理意识',
  `HLPFQK` varchar(50) NULL COMMENT '护理皮肤情况',
  `HLPFQKQT` varchar(50) NULL COMMENT '护理皮肤情况其他',
  `SKQK` varchar(50) NULL COMMENT '伤口情况',
  `SKQKQT` varchar(50) NULL COMMENT '伤口情况其他',
  `ZGQK` varchar(50) NULL COMMENT '置管情况',
  `HZZG` varchar(50) NULL COMMENT '患者转归',
  `SSZD` varchar(50) NULL COMMENT '术后指导',
  `SSZDQT` varchar(50) NULL COMMENT '术后指导其他',
  `CYZD` varchar(50) NULL COMMENT '出院指导',
  `CYZDZT` varchar(50) NULL COMMENT '出院指导其他',
  `HSQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护士签名',
  `HSQMRQ` datetime(0) NULL DEFAULT NULL COMMENT '护士签名日期',
  `YSQM` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '医师签名',
  `YSQMRQ` datetime(0) NULL DEFAULT NULL COMMENT '医师签名日期',
  `RQ` datetime(0) NULL DEFAULT NULL COMMENT '日期',
  `JGID` int(0) NULL DEFAULT NULL COMMENT '机构id',
  PRIMARY KEY (`JLXH`)
) COMMENT = '日间病房护理记录单';