ALTER TABLE `cis_bxsqd` 
ADD COLUMN `LXRDM` varchar(50) NULL COMMENT '领血人代码' AFTER `ZFRDM`,
ADD COLUMN `LXSJ` datetime(0) NULL COMMENT '领血时间' AFTER `LXRDM`,
ADD COLUMN `LXCZRDM` varchar(50) NULL COMMENT '领血操作人代码' AFTER `LXSJ`,
ADD COLUMN `LXCZSJ` datetime(0) NULL COMMENT '领血操作时间' AFTER `LXCZRDM`;