ALTER TABLE `cis_hzyz`
ADD COLUMN `ZTYCJL` decimal(8, 4) NULL COMMENT '组套一次剂量' AFTER `TJSJ`,
ADD COLUMN `ZTMRCS` int NULL COMMENT '组套每日次数' AFTER `ZTYCJL`,
ADD COLUMN `ZTYCSL` decimal(8, 4) NULL COMMENT '组套一次数量' AFTER `ZTMRCS`;