ALTER TABLE im_rzjz
ADD COLUMN JSWXJE decimal(10,2) null COMMENT '结算时收微信' AFTER JSPOSJE,
ADD COLUMN JSZFBJE decimal(10,2) NULL COMMENT '结算时收支付宝' AFTER JSWXJE,
ADD COLUMN JSGZJE decimal(10,2) NULL COMMENT '结算挂账金额' AFTER JSZFBJE,
ADD COLUMN JSZZJE decimal(10,2) NULL COMMENT '结算转账金额' AFTER JSGZJE,
ADD COLUMN SYJJWX decimal(10,2) NULL COMMENT '预交金收微信' AFTER SYJJPOS,
ADD COLUMN SYJJZFB decimal(10,2) NULL COMMENT '预交金收支付宝' AFTER SYJJWX,
ADD COLUMN SYJJEWM decimal(10,2) NULL COMMENT '预交金收二维码' AFTER SYJJZFB,
ADD COLUMN SYJJZZ decimal(10,2) NULL COMMENT '预交金收转账' AFTER SYJJEWM,
ADD COLUMN TYJJWX decimal(10,2) NULL COMMENT '退预交金微信' AFTER TYJJPOS,
ADD COLUMN TYJJZFB decimal(10,2) NULL COMMENT '退预交金支付宝' AFTER TYJJWX,
ADD COLUMN TYJJEWM decimal(10,2) NULL COMMENT '退预交金二维码' AFTER TYJJZFB,
ADD COLUMN TYJJZZ decimal(10,2) NULL COMMENT '退预交金转账' AFTER TYJJEWM;