ALTER TABLE `nis_cghljld` 
ADD COLUMN `YS` varchar(50) NULL COMMENT '意识' AFTER `DDZCID`,
ADD COLUMN `SPO2` decimal(10, 2) NULL COMMENT 'SpO2' AFTER `YS`,
ADD COLUMN `PF` varchar(50) NULL COMMENT '皮肤' AFTER `SPO2`,
ADD COLUMN `DGLX` varchar(50) NULL COMMENT '导管类型' AFTER `PF`,
ADD COLUMN `STW` varchar(50) NULL COMMENT '体位' AFTER `DGLX`,
ADD COLUMN `XYFS` varchar(50) NULL COMMENT '吸氧方式' AFTER `STW`,
ADD COLUMN `PT` varchar(50) NULL COMMENT '排痰' AFTER `XYFS`;

ALTER TABLE `nis_wzhld` 
ADD COLUMN `STW` varchar(50) NULL COMMENT '体位' AFTER `JGID`,
ADD COLUMN `PF` varchar(50) NULL COMMENT '皮肤' AFTER `STW`,
ADD COLUMN `XYFS` varchar(50) NULL COMMENT '吸氧方式' AFTER `PF`,
ADD COLUMN `PT` varchar(50) NULL COMMENT '排痰' AFTER `XYFS`;